from prettytable import PrettyTable
myTable=PrettyTable(["Name","Class","Roll_no.","Marks"])
myTable.add_row(['Ayush','X','1','91'])
myTable.add_row(['Abhinav','X','2','85'])
myTable.add_row(['Abhishek','X','3','74'])
myTable.add_row(['Aryan','X','4','87'])
myTable.add_row(['Aman','X','5','95'])
myTable.add_row(['Anshul','X','6','92'])
myTable.add_row(['Ankit','X','7','65'])
print(myTable)